version: '3.8'
services:
  game-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/gomoku
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    working_dir: /usr/src/app/server
    command: npm run dev
    depends_on:
      - mongo

  dev-server:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/client/node_modules
    working_dir: /usr/src/app/client
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: