version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/gomoku
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules
    working_dir: /usr/src/app/server
    command: npm run dev
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - mongo

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/client/node_modules
    working_dir: /usr/src/app/client
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    depends_on:
      - server

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: